export const USER_BACKEND_API="https://job-portal-backend-p9yw.onrender.com/api/v1/user"
export const JOB_BACKEND_API="https://job-portal-backend-p9yw.onrender.com/api/v1/job/"
export const APPLICATION_BACKEND_API="https://job-portal-backend-p9yw.onrender.com/api/v1/application/"
export const COMPANY_BACKEND_API="https://job-portal-backend-p9yw.onrender.com/api/v1/company/"
// export const USER_BACKEND_API="http://localhost:8080/api/v1/user"
// export const JOB_BACKEND_API="http://localhost:8080/api/v1/job/"
// export const APPLICATION_BACKEND_API="http://localhost:8080/api/v1/application/"
// export const COMPANY_BACKEND_API="http://localhost:8080/api/v1/company/"